package docs

// SyncVault API Documentation
// This file is auto-generated by swaggo/swag
// DO NOT EDIT

import (
	_ "embed"
	"fmt"
)

//go:embed openapi.yaml
var yamlSpec []byte

//go:embed swagger.json
var jsonSpec []byte

// SwaggerJSON returns the OpenAPI JSON specification
func SwaggerJSON() ([]byte, error) {
	if len(jsonSpec) == 0 {
		return nil, fmt.Errorf("swagger.json not found")
	}
	return jsonSpec, nil
}

// SwaggerYAML returns the OpenAPI YAML specification
func SwaggerYAML() ([]byte, error) {
	if len(yamlSpec) == 0 {
		return nil, fmt.Errorf("openapi.yaml not found")
	}
	return yamlSpec, nil
}
